nerfs:
  negative-reputation-on-killed:
    _desc: |
      If a villager transforms into a zombie villager, players around the villager (16 blocks)
      will get a temporary reputation of -25 (same as killing a villager, curing is permanent +20)
      on the transformed villager (may be shared to other villagers when cured)
    enabled: true
    radius: 16
    reputation-penalty: 25

lua:
  allow-io: false