name: BalancedVillagerTrades
version: @version@
main: com.jacky8399.balancedvillagertrades.BalancedVillagerTrades
api-version: 1.16
authors: [ jacky8399 ]
description: Balances 1.14+ trades

commands:
  balancedvillagertrades:
    permission: balancedvillagertrades.admin
    aliases: ["bvt"]
    usage: "/<command> reload"

permissions:
  balancedvillagertrades.admin:
    default: op